# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nvidia/github/video-logging

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nvidia/github/video-logging

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nvidia/github/video-logging/CMakeFiles /home/nvidia/github/video-logging/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nvidia/github/video-logging/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named logging_server

# Build rule for target.
logging_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logging_server
.PHONY : logging_server

# fast build rule for target.
logging_server/fast:
	$(MAKE) -f CMakeFiles/logging_server.dir/build.make CMakeFiles/logging_server.dir/build
.PHONY : logging_server/fast

#=============================================================================
# Target rules for targets named receive_from_rio_template

# Build rule for target.
receive_from_rio_template: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 receive_from_rio_template
.PHONY : receive_from_rio_template

# fast build rule for target.
receive_from_rio_template/fast:
	$(MAKE) -f CMakeFiles/receive_from_rio_template.dir/build.make CMakeFiles/receive_from_rio_template.dir/build
.PHONY : receive_from_rio_template/fast

#=============================================================================
# Target rules for targets named logging_client_demo

# Build rule for target.
logging_client_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logging_client_demo
.PHONY : logging_client_demo

# fast build rule for target.
logging_client_demo/fast:
	$(MAKE) -f CMakeFiles/logging_client_demo.dir/build.make CMakeFiles/logging_client_demo.dir/build
.PHONY : logging_client_demo/fast

logging_client_demo.o: logging_client_demo.cpp.o

.PHONY : logging_client_demo.o

# target to build an object file
logging_client_demo.cpp.o:
	$(MAKE) -f CMakeFiles/logging_client_demo.dir/build.make CMakeFiles/logging_client_demo.dir/logging_client_demo.cpp.o
.PHONY : logging_client_demo.cpp.o

logging_client_demo.i: logging_client_demo.cpp.i

.PHONY : logging_client_demo.i

# target to preprocess a source file
logging_client_demo.cpp.i:
	$(MAKE) -f CMakeFiles/logging_client_demo.dir/build.make CMakeFiles/logging_client_demo.dir/logging_client_demo.cpp.i
.PHONY : logging_client_demo.cpp.i

logging_client_demo.s: logging_client_demo.cpp.s

.PHONY : logging_client_demo.s

# target to generate assembly for a file
logging_client_demo.cpp.s:
	$(MAKE) -f CMakeFiles/logging_client_demo.dir/build.make CMakeFiles/logging_client_demo.dir/logging_client_demo.cpp.s
.PHONY : logging_client_demo.cpp.s

logging_server.o: logging_server.cpp.o

.PHONY : logging_server.o

# target to build an object file
logging_server.cpp.o:
	$(MAKE) -f CMakeFiles/logging_server.dir/build.make CMakeFiles/logging_server.dir/logging_server.cpp.o
.PHONY : logging_server.cpp.o

logging_server.i: logging_server.cpp.i

.PHONY : logging_server.i

# target to preprocess a source file
logging_server.cpp.i:
	$(MAKE) -f CMakeFiles/logging_server.dir/build.make CMakeFiles/logging_server.dir/logging_server.cpp.i
.PHONY : logging_server.cpp.i

logging_server.s: logging_server.cpp.s

.PHONY : logging_server.s

# target to generate assembly for a file
logging_server.cpp.s:
	$(MAKE) -f CMakeFiles/logging_server.dir/build.make CMakeFiles/logging_server.dir/logging_server.cpp.s
.PHONY : logging_server.cpp.s

receive_from_rio_template.o: receive_from_rio_template.cpp.o

.PHONY : receive_from_rio_template.o

# target to build an object file
receive_from_rio_template.cpp.o:
	$(MAKE) -f CMakeFiles/receive_from_rio_template.dir/build.make CMakeFiles/receive_from_rio_template.dir/receive_from_rio_template.cpp.o
.PHONY : receive_from_rio_template.cpp.o

receive_from_rio_template.i: receive_from_rio_template.cpp.i

.PHONY : receive_from_rio_template.i

# target to preprocess a source file
receive_from_rio_template.cpp.i:
	$(MAKE) -f CMakeFiles/receive_from_rio_template.dir/build.make CMakeFiles/receive_from_rio_template.dir/receive_from_rio_template.cpp.i
.PHONY : receive_from_rio_template.cpp.i

receive_from_rio_template.s: receive_from_rio_template.cpp.s

.PHONY : receive_from_rio_template.s

# target to generate assembly for a file
receive_from_rio_template.cpp.s:
	$(MAKE) -f CMakeFiles/receive_from_rio_template.dir/build.make CMakeFiles/receive_from_rio_template.dir/receive_from_rio_template.cpp.s
.PHONY : receive_from_rio_template.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... logging_server"
	@echo "... edit_cache"
	@echo "... receive_from_rio_template"
	@echo "... logging_client_demo"
	@echo "... rebuild_cache"
	@echo "... logging_client_demo.o"
	@echo "... logging_client_demo.i"
	@echo "... logging_client_demo.s"
	@echo "... logging_server.o"
	@echo "... logging_server.i"
	@echo "... logging_server.s"
	@echo "... receive_from_rio_template.o"
	@echo "... receive_from_rio_template.i"
	@echo "... receive_from_rio_template.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

